/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
//        // Logo
//        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/img/LOGO_XL.png"));
//        Image scaledImg = logoIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
//        JLabel logoLabel = new JLabel(new ImageIcon(scaledImg), SwingConstants.CENTER);
//        logoLabel.setBorder(BorderFactory.createEmptyBorder(60, 10, 5, 10));
//
//        // Tiêu đề
//        JLabel title = new JLabel("PHẦN MỀM QUẢN LÝ GIẶT ỦI");
//        title.setFont(new Font("Segoe UI", Font.BOLD, 28));
//        title.setHorizontalAlignment(SwingConstants.CENTER);
//        title.setForeground(new Color(0, 102, 204));
//        title.setBorder(BorderFactory.createEmptyBorder(10, 0, 5, 0)); 
//
//        // Phụ đề
//        JLabel subtitle = new JLabel("Dễ dàng - Nhanh chóng - Chính xác");
//        subtitle.setFont(new Font("Segoe UI", Font.ITALIC, 16));
//        subtitle.setHorizontalAlignment(SwingConstants.CENTER);
//        subtitle.setForeground(new Color(100, 100, 100));
//        subtitle.setBorder(BorderFactory.createEmptyBorder(0, 0, 35, 0));
//
//        // Panel chữ
//        JPanel textPanel = new JPanel(new GridLayout(2, 1));
//        textPanel.add(title);
//        textPanel.add(subtitle);
//        textPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 10, 0)); 
//
//        // Bố cục
//        setLayout(new BorderLayout(10, 20));
//        add(logoLabel, BorderLayout.CENTER);
//        add(textPanel, BorderLayout.SOUTH);
//        setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_XL.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PHẦN MỀM QUẢN LÝ GIẶT ỦI");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dễ dàng - Nhanh chóng - Chính xác");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
